### ISSUE TITLE
"args" conflict with some extentions?

### ISSUE THREAD

**Issue by WXZhao7** [tjx666/open-in-external-app#41]
Today I find that I can't use any `args` with this extension. Here is the settings I used.
```json
{
            "extensionName": "html",
            "apps": [
                {
                    "title": "firefox",
                    "openCommand": "/usr/bin/firefox",
                    "args": ["--private-window"]
                },
             ]
}
```

I could fix it by disable this three extension `Pylint`, `isort` and `flake8`. But the log shows that this may be relate to ms-python, amazing! I try to keep all extensions work togerther by deleting ` "args": ["--private-window"]` . I need your help!

![image](https://user-images.githubusercontent.com/56864878/199937051-5bef87c9-bfec-410c-8d5f-bf0bcd7f41e2.png)

> output of Extension Host
```log
2022-11-04 17:13:01.293 [error] TypeError: e.replace is not a function
    at String.replaceAll (/home/wxz/.vscode/extensions/ms-python.python-2022.19.13071014/out/client/extension.js:2:159086)
    at t.default (/home/wxz/.vscode/extensions/yutengjing.open-in-external-app-0.8.2/out/extension.js:1:181244)
    at t.open (/home/wxz/.vscode/extensions/yutengjing.open-in-external-app-0.8.2/out/extension.js:1:182712)
    at t.default (/home/wxz/.vscode/extensions/yutengjing.open-in-external-app-0.8.2/out/extension.js:1:178957)
    at handler (/home/wxz/.vscode/extensions/yutengjing.open-in-external-app-0.8.2/out/extension.js:1:175639)
    at s._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:111375)
    at s.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:112079)
    at l._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:13680)
    at l._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:13362)
    at l._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:12132)
    at l._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:10834)
    at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:8941
    at h.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at v.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
    at g.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
    at r.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:16515)
    at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:17104
    at h.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at v.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
    at g.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
    at r.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:16515)
    at o._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:21327)
    at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:18770
    at h.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at v.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
    at g.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
    at g.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:13346)
    at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:12476
    at Socket.i (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:24594)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2022-11-04 17:13:01.367 [trace] [vscode.html-language-features] provider DONE after 22165ms
2022-11-04 17:13:01.592 [trace] [vscode.html-language-features] provider DONE after 21191ms
2022-11-04 17:13:01.596 [trace] ExtHostCommands#executeCommand setContext
```

**Comment by tjx666** [comment]
Can you please provide a video of you steps to reproduce this issue?

**Comment by WXZhao7** [comment]
中文说方便点. 如果三个扩展和`arg`一起用, 不会有任何结果, 除非把extension Host的log level降低才能在Output -> Log(extension Host)里看到如上的内容.
等我我给你录一段看看

**Comment by WXZhao7** [comment]
找了个录屏, 瞧瞧. 虽然我觉得多半是python的锅
https://user-images.githubusercontent.com/56864878/199942317-32baca21-4c73-456e-9ac0-01a4f20e1840.mp4

**Comment by tjx666** [comment]
周末 debug 看看啥情况

**Comment by WXZhao7** [comment]
Thanks!

**Comment by tjx666** [comment]
最近 VSCode 插件系统貌似引入了个 bug，等 https://github.com/microsoft/vscode/issues/165539 处理了，我再处理这个问题。

**Comment by WXZhao7** [comment]
谢谢. 而且这个bug在Insider版本也有...
